# Generated by Django 4.2.23 on 2025-08-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20250831_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='Hello', upload_to='profiles/'),
            preserve_default=False,
        ),
    ]
